const USER = {
  CATEGORIZED_INTERESTS: [
    // Luxury
    { interest: "wineTasting", category: "luxury", score: 10 },
    { interest: "beerBrewing", category: "luxury", score: 8 },
    { interest: "fashion", category: "luxury", score: 9 },
    { interest: "gardening", category: "luxury", score: 6 },
    { interest: "carRestoration", category: "luxury", score: 8 },
    { interest: "homeBrewing", category: "luxury", score: 7 },
    { interest: "beerTasting", category: "luxury", score: 8 },
    { interest: "cookingClasses", category: "luxury", score: 7 },
    { interest: "artClasses", category: "luxury", score: 8 },
  
    // Adventurous
    { interest: "hiking", category: "adventurous", score: 10 },
    { interest: "surfing", category: "adventurous", score: 9 },
    { interest: "snowboarding", category: "adventurous", score: 10 },
    { interest: "skiing", category: "adventurous", score: 9 },
    { interest: "fishing", category: "adventurous", score: 8 },
    { interest: "hunting", category: "adventurous", score: 8 },
    { interest: "kayaking", category: "adventurous", score: 9 },
    { interest: "canoeing", category: "adventurous", score: 8 },
    { interest: "scubaDiving", category: "adventurous", score: 10 },
    { interest: "snorkeling", category: "adventurous", score: 9 },
    { interest: "rockClimbing", category: "adventurous", score: 10 },
    { interest: "camping", category: "adventurous", score: 9 },
    { interest: "backpacking", category: "adventurous", score: 10 },
    { interest: "urbanExploration", category: "adventurous", score: 8 },
  
    // Creative
    { interest: "photography", category: "creative", score: 9 },
    { interest: "painting", category: "creative", score: 10 },
    { interest: "drawing", category: "creative", score: 10 },
    { interest: "crafting", category: "creative", score: 9 },
    { interest: "knitting", category: "creative", score: 8 },
    { interest: "sewing", category: "creative", score: 9 },
    { interest: "woodworking", category: "creative", score: 9 },
    { interest: "writing", category: "creative", score: 8 },
    { interest: "poetry", category: "creative", score: 9 },
    { interest: "acting", category: "creative", score: 10 },
    { interest: "standUpComedy", category: "creative", score: 9 },
    { interest: "magicTricks", category: "creative", score: 8 },
    { interest: "cosplay", category: "creative", score: 9 },
    { interest: "modelBuilding", category: "creative", score: 8 },
    { interest: "aquariumKeeping", category: "creative", score: 7 },
    { interest: "bonsaiTrees", category: "creative", score: 8 },
    { interest: "trampolining", category: "creative", score: 7 },
  
    // Intellectual
    { interest: "reading", category: "intellectual", score: 9 },
    { interest: "blogging", category: "intellectual", score: 8 },
    { interest: "vlogging", category: "intellectual", score: 7 },
    { interest: "puzzleSolving", category: "intellectual", score: 10 },
    { interest: "languageLearning", category: "intellectual", score: 9 },
    { interest: "cultureExploration", category: "intellectual", score: 8 },
    { interest: "history", category: "intellectual", score: 9 },
    { interest: "philosophy", category: "intellectual", score: 9 },
    { interest: "science", category: "intellectual", score: 9 },
    { interest: "technology", category: "intellectual", score: 9 },
    { interest: "robotics", category: "intellectual", score: 8 },
    { interest: "coding", category: "intellectual", score: 10 },
    { interest: "investing", category: "intellectual", score: 9 },
    { interest: "entrepreneurship", category: "intellectual", score: 9 },
    { interest: "astronomy", category: "intellectual", score: 10 },
    { interest: "astrology", category: "intellectual", score: 7 },
    { interest: "puzzleSolving", category: "intellectual", score: 9 },
  
    // Social
    { interest: "movies", category: "social", score: 7 },
    { interest: "music", category: "social", score: 8 },
    { interest: "dancing", category: "social", score: 9 },
    { interest: "fitness", category: "social", score: 8 },
    { interest: "yoga", category: "social", score: 7 },
    { interest: "playingInstruments", category: "social", score: 9 },
    { interest: "singing", category: "social", score: 10 },
    { interest: "sports", category: "social", score: 8 },
    { interest: "basketball", category: "social", score: 9 },
    { interest: "soccer", category: "social", score: 9 },
    { interest: "football", category: "social", score: 8 },
    { interest: "baseball", category: "social", score: 8 },
    { interest: "tennis", category: "social", score: 7 },
    { interest: "golf", category: "social", score: 7 },
    { interest: "bowling", category: "social", score: 7 },
    { interest: "martialArts", category: "social", score: 8 },
    { interest: "fencing", category: "social", score: 7 },
    { interest: "archery", category: "social", score: 7 },
    { interest: "boardGames", category: "social", score: 8 },
    { interest: "cardGames", category: "social", score: 7 },
    { interest: "foodFestivals", category: "social", score: 9 },
    { interest: "musicFestivals", category: "social", score: 10 },
    { interest: "comicConventions", category: "social", score: 8 },
    { interest: "rollerblading", category: "social", score: 7 },
    { interest: "iceSkating", category: "social", score: 8 },
    { interest: "parkour", category: "social", score: 7 },
  ]
}

export { USER }